= Handling Exception Message


== Structure

[cols="3,1,4", options="header"]
|===
| Element | Usage | Description
3+| HandlingException
| + Version | 1..1 | Version of schema
| + Exception | 1..1 | Exception
| --+ Code | 1..1 | Code according to code list
| --+ Description | 1..1 | Human readable description of the exception.
| + StandardBusinessDocumentHeader | 1..1 | SBDH of origin which the exception is raised.
|===

== Code lists


=== Exception code

[cols="1,5", options="header"]
|===
| Code | Description
h| 000 | Not in use +
_All OK. Received, decrypted, legible header/metadata_
h| 001 | Signature Validation error inner ASiC
h| 002 | Signature Validation error outer ASiC
h| 003 | SBDH error
h| 004 | Technical authentication error +
_Technical validation towards PKI and revocation status. Business rules related to authentication based upon PKI is out of scope for this code._
h| 005 | Decryption error
h| 006 | Local routing information/metadata error +
_Used only in cases where business rules are unable to handle content because of errors in metadata file. Not a replacement for situations where business messages may be used._
h| 007 | Error in decoding Base64
h| 008 | Unable to process Outer ASiC
h| 009 | Unable to process Inner ASiC
h| 099 | Other +
_Any use of this code requires reporting to the authority responsible for the transport infrastructure._
|===
